run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - revive
    - errcheck
    - gosimple
    - ineffassign
    - unused

issues:
  exclude-use-default: false
  max-same-issues: 3
